package com.fifteen.profile;

import com.fifteen.database.User;
import com.fifteen.settings.EventSettings;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Locale;

//@author Jorge

public class ProfilePage extends JFrame {
  private JFrame frame;
  private JPanel panel1;
  private JLabel profileUsername;
  private JPanel conTitle;
  private JButton editContact;
  private JLabel profileEmail;
  private JLabel welcomLabel;
  private JLabel cpdLabel;
  private JButton settingsButton;
  private JLabel profileID;
  private JLabel idLabel;

  public ProfilePage(User user) {
    frame = new JFrame("Profile");

    frame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    frame.setPreferredSize(new Dimension(500, 450));
    frame.setResizable(false);

    frame.add(panel1);
    frame.pack();
    frame.setLocationRelativeTo(null);
    frame.setVisible(true);
    editContact.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        new EditContact();
      }
    });

    profileUsername.setText(user.getUsername());
    profileEmail.setText(user.getEmail());
    profileID.setText(user.getUserID());

    settingsButton.addActionListener(new ActionListener() {
      @Override
      public void actionPerformed(ActionEvent e) {
        if (user.getEmail().equals("Guest")) {

          JOptionPane.showMessageDialog(frame, "You are not logged in!",
              "Error",
              JOptionPane.ERROR_MESSAGE);
        } else {
          new EventSettings(user);
        }
      }
    });
  }

  {
    // GUI initializer generated by IntelliJ IDEA GUI Designer
    // >>> IMPORTANT!! <<<
    // DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    panel1 = new JPanel();
    panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    conTitle = new JPanel();
    conTitle.setLayout(new GridLayoutManager(12, 3, new Insets(0, 0, 0, 0), -1, -1));
    panel1.add(conTitle,
        new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    profileUsername = new JLabel();
    Font profileUsernameFont = this.$$$getFont$$$("Fira Code", Font.BOLD, 20, profileUsername.getFont());
    if (profileUsernameFont != null)
      profileUsername.setFont(profileUsernameFont);
    profileUsername.setText("");
    conTitle.add(profileUsername,
        new GridConstraints(2, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE,
            GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    profileEmail = new JLabel();
    profileEmail.setEnabled(false);
    Font profileEmailFont = this.$$$getFont$$$("Fira Code", Font.PLAIN, 14, profileEmail.getFont());
    if (profileEmailFont != null)
      profileEmail.setFont(profileEmailFont);
    profileEmail.setText("");
    conTitle.add(profileEmail, new GridConstraints(3, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE,
        GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    final Spacer spacer1 = new Spacer();
    conTitle.add(spacer1, new GridConstraints(1, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL,
        1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    final JLabel label1 = new JLabel();
    label1.setText("Contacts");
    conTitle.add(label1, new GridConstraints(9, 0, 1, 3, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
        GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    final Spacer spacer2 = new Spacer();
    conTitle.add(spacer2, new GridConstraints(8, 0, 1, 3, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL,
        1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    editContact = new JButton();
    editContact.setText("Edit Contacts");
    conTitle.add(editContact,
        new GridConstraints(10, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
            GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    final Spacer spacer3 = new Spacer();
    conTitle.add(spacer3, new GridConstraints(11, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL,
        1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    welcomLabel = new JLabel();
    Font welcomLabelFont = this.$$$getFont$$$("Fira Code", Font.ITALIC, 12, welcomLabel.getFont());
    if (welcomLabelFont != null)
      welcomLabel.setFont(welcomLabelFont);
    welcomLabel.setText("Welcome,");
    conTitle.add(welcomLabel, new GridConstraints(0, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
        GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    final Spacer spacer4 = new Spacer();
    conTitle.add(spacer4, new GridConstraints(4, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL,
        1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
    cpdLabel = new JLabel();
    cpdLabel.setText("Change Profile Details");
    conTitle.add(cpdLabel, new GridConstraints(6, 0, 1, 2, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
        GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    settingsButton = new JButton();
    settingsButton.setText("Settings");
    conTitle.add(settingsButton,
        new GridConstraints(7, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL,
            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
            GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    profileID = new JLabel();
    Font profileIDFont = this.$$$getFont$$$("Fira Code", Font.PLAIN, 10, profileID.getFont());
    if (profileIDFont != null)
      profileID.setFont(profileIDFont);
    profileID.setText("");
    conTitle.add(profileID, new GridConstraints(5, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE,
        GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    idLabel = new JLabel();
    Font idLabelFont = this.$$$getFont$$$("Fira Code", Font.PLAIN, 10, idLabel.getFont());
    if (idLabelFont != null)
      idLabel.setFont(idLabelFont);
    idLabel.setText("ID:");
    conTitle.add(idLabel, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE,
        GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
  }

  /**
   * @noinspection ALL
   */
  private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
    if (currentFont == null)
      return null;
    String resultName;
    if (fontName == null) {
      resultName = currentFont.getName();
    } else {
      Font testFont = new Font(fontName, Font.PLAIN, 10);
      if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
        resultName = fontName;
      } else {
        resultName = currentFont.getName();
      }
    }
    Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(),
        size >= 0 ? size : currentFont.getSize());
    boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
    Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize())
        : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
    return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return panel1;
  }

}
