package com.fifteen.events.local;

import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import lombok.Getter;

/**
 * Event class to be create whenever the user created a new event. This event
 * will be stored locally inside our local.db file and will be sync to the
 * remote database every minutes or so. Each event will have an event ID
 * to unique identify it, the ID is created by the user email_a unique ID
 * generated by the UUID.
 * 
 * @author Triet Huynh
 */
@Getter
public class Event {
  private String eventID;
  private String eventName;
  private Calendar calendar;
  private Set<String> participants = new HashSet<String>();
  private Location location;
  private Priority priority;

  public Event(String userEmail, String eventName, Calendar calendar, Set<String> participants,
      Location location, Priority priority) {
    this.eventID = userEmail + "_" + UUID.randomUUID().toString();
    this.eventName = eventName;
    this.calendar = calendar;
    this.location = location;
    this.participants.addAll(participants);
    this.priority = priority;
  }

  public void addParticipant(String[] participantsEmails) {
    for (int i = 0; i < participantsEmails.length; i++) {
      this.participants.add("\"" + participantsEmails[i] + "\"");
    }

  }
}
