package com.fifteen.events.local;

import java.util.GregorianCalendar;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import lombok.Getter;

/**
 * Event class to be create whenever the user created a new event. This event
 * will be stored locally inside our local.db file and will be sync to the
 * remote database every minutes or so. Each event will have an event ID
 * to unique identify it, the ID is created by the user email_a unique ID
 * generated by the UUID.
 * 
 * @author Triet Huynh
 */
@Getter
public class Event {
  private String eventID = "null";
  private String eventName = "null";
  private String eventDescription = "null";
  private GregorianCalendar dayOfEvent;
  private int event_duration_minute = 0;
  private Set<String> participants_email = new HashSet<String>();
  private Location location;
  private Priority priority;
  private int priority_score;

  public Event(String userEmail, String eventName, String eventDescription, GregorianCalendar dayOfEvent,
      Set<String> participants_email, Location location, Priority priority, int priority_score,
      int event_duration_minute) {
    this.eventID = UUID.randomUUID().toString();
    this.eventName = eventName;
    this.eventDescription = eventDescription;
    this.dayOfEvent = dayOfEvent;
    this.event_duration_minute = event_duration_minute;
    this.participants_email.addAll(participants_email);
    this.location = location;
    this.priority = priority;
    this.priority_score = priority_score;
  }

  public void addParticipant(String[] participantsEmails) {
    for (int i = 0; i < participantsEmails.length; i++) {
      this.participants_email.add("\"" + participantsEmails[i] + "\"");
    }

  }
}
